"""Synthetic transcripts only: no patient material belongs in this repository."""
import json
import logging

import pytest

from src.chronology_agent import ChronologyAgent
from src.deposition import (DepositionReviewRequired, dates_in_text, prepare_document,
                            source_chunks, summarize, cover_dates)


def transcript(date='July 16th, 2026', name='Jamie Example'):
    return (f'IN THE CIRCUIT COURT\nDEPOSITION OF {name}\nDATE: {date}\n'
            + '\n'.join(f'{i * 2 + 1} Q. Did you have pain?\n{i * 2 + 2} A. I recall back pain.'
                        for i in range(8)))


def agent():
    a = ChronologyAgent.__new__(ChronologyAgent)
    a.logger = logging.getLogger('deposition-test')
    a.model = 'test-model'
    return a


def metadata():
    return {'date': '07/16/2026', 'witness': 'Jamie Example', 'credentials': '',
            'date_quote': 'DATE: July 16th, 2026',
            'witness_quote': 'DEPOSITION OF Jamie Example', 'credentials_quote': ''}


def statements():
    return {'statements': [{'text': 'The patient testified that they recalled back pain.',
                            'evidence': ['2 A. I recall back pain.']}]}


def test_combined_summary_and_toc_excluded():
    prefix = 'Deposition Summary\nTranscript Text\nOverall Summary\nInvented surgery.\n'
    content = prefix + 'Transcript Text\n' + transcript()
    doc = prepare_document('combined.txt', content)
    assert doc['content'] == transcript()
    assert 'Invented surgery' not in ''.join(p['content'] for p in source_chunks(doc, 100))
    assert doc['excluded_prefix_chars'] > len(prefix)


def test_unlabeled_transcript_cover_after_summary():
    doc = prepare_document('bundle.txt', 'Deposition Summary\nInvented surgery.\n' + transcript())
    assert doc['content'] == transcript()


def test_wrapper_disclaimer_does_not_disqualify_real_transcript():
    text = transcript() + '\nThis content has been generated by an artificial intelligence language model.'
    assert prepare_document('record.txt', text)['content'] == text


def test_standalone_with_nondeposition_filename_and_clinical_reference():
    assert prepare_document('Example.txt', transcript())['document_type'] == 'deposition'
    assert prepare_document('Office.txt', '04/01/2026. The patient discussed a deposition. Plan: Therapy.') is None


@pytest.mark.parametrize('text', ['Deposition Summary\nWitness had surgery.',
    'Deposition Summary\nNo validated boundary\n' + transcript().replace('IN THE CIRCUIT COURT\nDEPOSITION OF Jamie Example\n', 'deposition\n')])
def test_summary_only_or_unclear_boundary_requires_review(text):
    with pytest.raises(DepositionReviewRequired):
        prepare_document('deposition.txt', text)


def test_dates_and_lossless_chunks():
    assert dates_in_text('July 16th, 2026 and APRIL 2ND, 2025 and 02/31/2026') == {'07/16/2026', '04/02/2025'}
    doc = prepare_document('witness.txt', transcript())
    assert ''.join(p['content'] for p in source_chunks(doc, 73)) == doc['content']
    assert cover_dates(prepare_document('witness.txt', transcript() + '\nQ. Previous deposition April 2, 2025?')) == {'07/16/2026'}


def test_one_dated_paragraph_and_retained_evidence():
    calls, responses = [], iter([metadata(), statements()])
    def call(prompt, **kw):
        calls.append(prompt)
        return json.dumps(next(responses))
    doc = prepare_document('witness.txt', transcript())
    entry, evidence = summarize(doc, call)
    assert entry == '07/16/2026. Jamie Example, Deposition. The patient testified that they recalled back pain.'
    assert '\n' not in entry
    assert evidence['statements'] == statements()['statements']
    assert evidence['transcript_sha256'] == doc['transcript_sha256']
    assert 'never separate dated visits' in calls[-1]


@pytest.mark.parametrize('field,value', [('date', '07/15/2026'), ('witness', 'Wrong Person'),
                                       ('credentials', 'MD'), ('date_quote', 'July 15th, 2026')])
def test_unsubstantiated_identity_is_not_saved(field, value):
    data = {**metadata(), field: value}
    with pytest.raises(DepositionReviewRequired):
        summarize(prepare_document('source.txt', transcript()), lambda *a, **k: json.dumps(data))


def test_unsupported_quote_rejected():
    result = statements()
    result['statements'][0]['evidence'] = ['I had surgery.']
    responses = iter([metadata(), result])
    with pytest.raises(DepositionReviewRequired):
        summarize(prepare_document('source.txt', transcript()), lambda *a, **k: json.dumps(next(responses)))


def test_long_transcript_all_parts_read_then_one_summary():
    doc = prepare_document('source.txt', transcript() + '\n' + ('Q. Symptoms?\nA. Pain continued.\n' * 4500) + '\nFINAL TESTIMONY')
    calls = []
    def call(prompt, **kw):
        calls.append(prompt)
        if len(calls) == 1:
            return json.dumps(metadata())
        if 'Extract relevant testimony from this slice' in prompt:
            return json.dumps({'statements': [{'text': 'The witness reported continued pain.',
                'evidence': ['A. Pain continued.']}]})
        return json.dumps(statements())
    entry, evidence = summarize(doc, call)
    assert entry.count('07/16/2026.') == 1
    assert len(calls) == len(source_chunks(doc)) + 2
    assert 'FINAL TESTIMONY' in calls[-2]
    assert evidence['transcript_chars_read'] == len(doc['content'])


def test_batch_isolation_and_unsafe_resume_preserves_files(tmp_path, monkeypatch):
    a = agent()
    docs = [{'filename': 'clinic', 'content': '04/01/2026 clinical'},
            prepare_document('witness.txt', transcript()),
            {'filename': 'clinic2', 'content': '04/02/2026 clinical'}]
    a._read_extracted_files = lambda _: docs
    assert [len(b) for b in a._plan_batches(docs)] == [1, 1, 1]
    old = tmp_path / 'batch_001.md'
    old.write_text('old clinical result')
    with pytest.raises(DepositionReviewRequired, match='predate'):
        a.generate_batches('', str(tmp_path))
    assert old.read_text() == 'old clinical result'


def test_generation_resume_and_source_change(tmp_path):
    a = agent()
    doc = prepare_document('witness.txt', transcript())
    a._read_extracted_files = lambda _: [doc]
    responses = iter([metadata(), statements()])
    a._call_api_with_retry = lambda *a, **k: json.dumps(next(responses))
    assert a.generate_batches('', str(tmp_path))['success']
    assert (tmp_path / 'batch_001.deposition.json').exists()
    a._call_api_with_retry = lambda *a, **k: pytest.fail('Resume must not reprocess')
    assert a.generate_batches('', str(tmp_path))['batches_skipped_from_disk'] == 1
    doc['content'] += '\nNew testimony'
    with pytest.raises(DepositionReviewRequired, match='different sources'):
        a.generate_batches('', str(tmp_path))


def test_assembly_keeps_paragraph_and_evidence(tmp_path):
    a = agent()
    sources, batches, output = [tmp_path / name for name in ('sources', 'batches', 'output')]
    sources.mkdir()
    (sources / 'witness.txt').write_text(transcript())
    responses = iter([metadata(), statements()])
    a._call_api_with_retry = lambda *a, **k: json.dumps(next(responses))
    a.generate_batches(str(sources), str(batches))
    a.extract_header = lambda *a: {'patient_name': 'JAMIE EXAMPLE', 'date_of_birth': '[See Records]', 'date_of_injury': '[See Records]'}
    a.generate_summary_and_gaps = lambda *a: {'summary_md': 'Review testimony.', 'gaps_md': 'Human review required.'}
    a.assemble_outputs(str(sources), str(batches), str(output))
    result = json.loads((output / 'chronology.json').read_text())
    assert result['chronology_markdown'].count('07/16/2026. Jamie Example, Deposition.') == 1
    assert result['deposition_evidence'][0]['source_file'] == 'witness.txt'
    assert result['deposition_evidence'][0]['statements'] == statements()['statements']


def test_reading_summary_only_does_not_silently_drop_source(tmp_path):
    (tmp_path / 'summary.txt').write_text('Deposition Summary\nNo testimony')
    with pytest.raises(DepositionReviewRequired):
        agent()._read_extracted_files(str(tmp_path))


def test_verification_all_transcript_parts_and_no_preface(tmp_path):
    a = agent()
    text = 'Deposition Summary\nFALSE PREFACE\nTranscript Text\n' + transcript() + '\n' + 'x' * 85000 + 'FINAL ANSWER'
    source = tmp_path / 'sources'
    source.mkdir()
    (source / 'witness.txt').write_text(text)
    path = tmp_path / 'chronology.md'
    path.write_text('07/16/2026. Jamie Example, Deposition. The patient recalled pain.')
    reviewed = []
    a._verify_entry_batch = lambda e, docs: reviewed.extend(docs) or 'No issues found.'
    result = a.verify_chronology(str(path), str(source))
    assert result['entries_reviewed'] == 1
    assert ''.join(d['content'] for d in reviewed).endswith('FINAL ANSWER')
    assert 'FALSE PREFACE' not in ''.join(d['content'] for d in reviewed)
    assert result['documents_checked'] == 5


def test_clinical_date_cannot_match_only_recalled_deposition_date(tmp_path):
    a = agent()
    a._read_extracted_files = lambda _: [prepare_document('source.txt', transcript() + '\nRecall 04/01/2026.')]
    path = tmp_path / 'chronology.md'
    path.write_text('04/01/2026. Clinic. Visit.')
    result = a.verify_chronology(str(path), '')
    assert result['entries_unreviewed'] == 1


def test_two_sessions_remain_separate_and_sorted():
    a = agent()
    docs = [prepare_document('july.txt', transcript()),
            prepare_document('april.txt', transcript('April 2nd, 2025'))]
    assert len(a._plan_batches(docs)) == 2
    first = '04/02/2025. Jamie Example, Deposition. The patient reported pain.'
    second = '07/16/2026. Jamie Example, Deposition. The patient recalled treatment.'
    assert a._sort_entries_chronologically(second + '\n\n' + first) == first + '\n\n' + second
